version: "3.9"

services:
  devopsdb:
    image: devi1999/dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    image: devi1999/chatpp
    ports:
      - "1111:8080"
    deploy:
      replicas: 1
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
